-- creating customer table--
create table movie 
(
  name varchar(30),
  showdate date,
  showtime varchar(10),
  price float,
  seat number(11),
  theatrename varchar(50)
);
create table registration
(
 cid number(10)generated by default on null as identity,
 username varchar(50) unique not null,
 name varchar(50) not null,
 phone number(10) not null unique,
 email varchar(10) not null unique,
 password varchar(5) not null unique,
 primary key(cid)
);
--modifying the email column 
alter table registration modify email varchar(50);

--using desc to view the structure of created tables 
desc movie;
desc registration;

--using delete query to empty the table 
delete from registration;
delete from movie;